//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public int TypeID { get; set; }
        public int BrandID { get; set; }
        public string Model { get; set; }
        public int Quantity { get; set; }
        public decimal DistributorPrice { get; set; }
        public decimal SuggestedRetailPrice { get; set; }
        public int DealerID { get; set; }
    }
}
