//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuckyDrawWinner
    {
        public int Id { get; set; }
        public int RaffleId { get; set; }
        public int ProductId { get; set; }
        public int ParticipantId { get; set; }
        public string RaffleReferenceNumber { get; set; }
        public int LuckyDrawPrizeId { get; set; }
    }
}
