//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfSale
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string SellerName { get; set; }
    }
}
