//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    
    public partial class PointOfSalesViewModel
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string ReceiptNumber { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
    }
}
