//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Raffle
    {
        public int Id { get; set; }
        public System.DateTime DrawDate { get; set; }
        public decimal EntryPrice { get; set; }
        public int MaxEntries { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
