//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLibrary.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaffleEntry
    {
        public int Id { get; set; }
        public int RaffleId { get; set; }
        public int ParticipantId { get; set; }
        public System.DateTime TransactionDateTime { get; set; }
        public string PaymentReceipt { get; set; }
        public string RaffleReferenceNumber { get; set; }
        public decimal PaidAmount { get; set; }
        public int PaymentMethod { get; set; }
        public Nullable<int> LuckyNumber1 { get; set; }
        public Nullable<int> LuckyNumber2 { get; set; }
        public Nullable<int> LuckyNumber3 { get; set; }
        public Nullable<int> RafflePrizeId { get; set; }
        public Nullable<int> ProductId { get; set; }
    }
}
